name: BuildAndDeploy

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output publish --no-restore

    - name: Set up Node
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'      

    - name: Install Surge CLI
      run: npm install -g surge        

    - name: Deploy application
      run: surge ./publish ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}